resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/WASH7P.fna"

vep:
  container: "docker://ensemblorg/ensembl-vep:release_99.0"
  vep_cache:  VEP/homo_sapiens
  mode: "--database"
  extra: " --af  "

calculate_seqrun_background:
  container: "docker://python:3.9.7-slim"
