resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/WASH7P.fna"

snpeff:
  container: "docker://hydragenetics/snpeff:5.0"
  db: "SnpEff/GRCh38"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  VEP/homo_sapiens
  mode: "--database"
  extra: " --af  "

calculate_seqrun_background:
  container: "docker://python:3.9.7-slim"
