resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.2"

reference:
  fasta: "reference/WASH7P.fna"
  artifacts: "reference/artifact_panel_chr1.tsv"
  background: "reference/background_panel_HES45.tsv"

hotspot_annotation:
  hotspots: "reference/hotspots_combined_small.csv"
  chr_translation_file: "reference/hotspot_report.chr.translation.hg19"

simple_sv_annotation:
  container: "docker://hydragenetics/simple_sv_annotation:2019.02.18"
  panel: "reference/panel.txt"
  fusion_pairs: "reference/fusion_pairs.txt"

snpeff:
  container: "docker://hydragenetics/snpeff:5.0"
  db: "SnpEff/GRCh38.99"

stranger:
  container: "docker://hydragenetics/stranger:0.8.1"
  catalog: "stranger/variant_catalog_grch38.json"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  VEP/homo_sapiens
  mode: "--database"
  extra: "  --pick --af "
